apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: docker-cleanup
  namespace: kube-system
  labels:
    k8s-app: docker-cleanup
spec:
  selector:
    matchLabels:
      name: docker-cleanup
  template:
    metadata:
      labels:
        name: docker-cleanup
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: docker-cleanup
        image: docker
        command: [ "/bin/sh" ]
        args: ["-c", "while true; do time_until=$(docker images | grep greenplum-for-kubernetes | awk '{print  $3}' | xargs docker inspect -f '{{ .Created }}' | awk ' NR ==
                                     3 {print $1}'); if [ ! ${time_until} = \"\" ]; then docker image prune --all --force --filter \"until=${time_until}\"; fi; sleep 10m ; done"]
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
      terminationGracePeriodSeconds: 30
      volumes:
      - name: dockersock
        hostPath:
          path: /var/vcap/data/sys/run/docker/docker.sock
