---
# specify the url for the docker image for the operator, e.g. gcr.io/<my_project>/greenplum-operator
operatorImageRepository: jike21/greenplum-operator
operatorImageTag: v1-20231104

# specify the docker image for greenplum instance, e.g. gcr.io/<my_project>/greenplum-instance
greenplumImageRepository: jike21/greenplum-gp4k
greenplumImageTag:  jike21/greenplum-gp4k:v1-20231104

operatorWorkerSelector: {}
