apiVersion: batch/v1
kind: Job
metadata:
  name: "greenplum-operator-fetch-test"
spec:
  template:
    metadata:
      name: "greenplum-operator-fetch-test"
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: regsecret
      containers:
        - name: greenplum-operator-fetch-test
          image: GREENPLUM_OPERATOR_IMAGE
          imagePullPolicy: Always
          command: ["echo", 'GREENPLUM-OPERATOR TEST OK']
